name: "SIG Create Form"
description: "Request form to create a SIG under the OAI"
title: "[Create SIG]: "
labels: SIG, invitation-request
assignees:
  - namdeirf
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out the SIG creation form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com [Note this email will be displayed publicly]
    validations:
      required: false
  - type: textarea
    id: scope
    attributes:
      label: Scope of SIG
      description: What is the scope of the project you are working on
      placeholder: Tell us what problem you want to address, expected outcome, and the ideal contributor profile (experience, skills, domain expertise, etc.)
      value: "Scope of contribution"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Class
      description: What is the class of SIG you want to create?
      options:
        - Technical (Narrow scope that addresses a specific technical need, feature or enhancement)
        - Industry (Broad scope that addresses a series of issues that pertains to a specific industry domain)
    validations:
      required: true
  - type: dropdown
    id: Versions
    attributes:
      label: What versions of the spec do you want your changes to be incorporated in?
      multiple: true
      options:
        - Current
        - Next
        - Some future release
  - type: dropdown
    id: Community
    attributes:
      label: Where will your community gather
      multiple: true
      options:
        - Slack
        - Discord
        - GitHub        
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
