name: "SIG Create Form"
description: "Request form to create a SIG under the OAI. Please provide a brief title, description, and fill out the details below and we'll get back to you ASAP."
title: "[Request to Create SIG]: "
labels: SIG, invitation-request
assignees:
  - namdeirf
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out the SIG creation form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com [Note this email will be displayed publicly]
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Scope of SIG
      description: A brief description, ideally a single paragraph that describes your SIG.
      value: "Scope of contribution"
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: SOW 
      description: A detailed statement of work (SOW) defining what your SIG will accomplish.
      value: "Scope of contribution"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Class
      description: What is the class of SIG you want to create? Technical SIGs are narrow scope that addresses specific, known technical needs, limitations, features or enhancements. Industry SIGs are created to address a series of domain specific needs which may or may not require in changes to the spec.
      options:
        - Technical SIG
        - Industry SIG
    validations:
      required: true
  - type: dropdown
    id: history
    attributes:
      label: History
      description: Is this an existing group that you want to move to the OAI, or are you forming this group for the first time.
      options:
        - Pre-existing group we want to move to the OAI
        - A new group we want to create under the OAI
    validations:
      required: true
  - type: dropdown
    id: Versions
    attributes:
      label: What versions of the spec do you want your changes to be incorporated in?
      multiple: true
      options:
        - Current
        - Next
        - Some future release
  - type: dropdown
    id: Cadence
    attributes:
      label: How often do you intend to need to meet
      multiple: false
      options:
        - Weekly
        - Every other week
        - Monthly
        - Every other month
        - Quarterly
        - Annual
        - Ad hoc
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
